export default {
  account: 'account-outline',
  addition: 'plus-box',
  arrowDown: 'chevron-down',
  arrowLeft: 'chevron-left',
  arrowRight: 'chevron-right',
  arrowUp: 'chevron-up',
  backspace: 'backspace-outline',
  check: 'check',
  clock: 'clock-outline',
  close: 'close',
  cog: 'cog-outline',
  correct: 'checkbox-marked-circle-outline',
  division: 'division-box',
  history: 'history',
  incorrect: 'stop-circle-outline',
  list: 'format-list-bulleted',
  multiplication: 'multiplication-box',
  reload: 'reload',
  save: 'content-save-outline',
  star: 'star-outline',
  subtraction: 'minus-box',
  trashCan: 'trash-can-outline',
};
