export default {
  language: 'English',
  buttons: {
    start: 'begin',
    nextTask: 'next',
    finish: 'finish',
    saveTask: 'save',
    submitTasks: 'submit',
    reviewTasks: 'review',
    close: 'close',
    tryAgain: 'try again',
    showResults: 'show results',
    rateOnAppStore: 'rate us on app store',
    yes: 'Yes',
    no: 'No',
  },
  notifications: {
    enterNumber: 'Please enter a number',
    selectOperation: 'Please select at least one arithmetic operation',
    selectChallenge: 'Please select at least one problem type',
    selectNumDigits1: 'Please select at least one digit for the first number',
    selectNumDigits2: 'Please select at least one digit for the second number',
    clearHistory: 'Are you sure you want to clear entire history?',
    historyIsEmpty: 'Your history is empty.',
  },
  numDigits: {
    title1: 'First number',
    title2: 'Second number',
    one: 'single digit',
    two: 'two digits',
    three: 'three digits',
    four: 'four digits',
  },
  numTasks: {
    title: 'Number of questions',
    ten: 'ten',
    twenty: 'twenty',
    fifty: 'fifty',
    hundred: 'one hundred',
  },
  operations: {
    title: 'Arithmetic operations',
    addition: 'addition',
    subtraction: 'subtraction',
    multiplication: 'multiplication',
    division: 'division',
  },
  pageTitles: {
    hello: 'Hello!',
    settings: 'Settings',
    task: 'Question',
    outOf: 'of',
    intermitResults: 'Your answers',
    results: 'Results',
    history: 'History',
  },
  results: {
    title: 'Results',
    total: 'number of questions',
    correct: 'right answers',
    incorrect: 'wrong answers',
    duration: 'time taken',
  },
  sectionTitles: {
    selectLanguage: 'Select language',
  },
  statistics: {
    title: 'Statistics',
  },
  tasks: {
    title: 'Problem type',
    solveA: 'find the first number',
    solveB: 'find the second number',
    solveC: 'find the result',
  },
  developedBy: 'Developed by',
};
