export default {
  language: 'Lietuviškai',
  buttons: {
    start: 'pradėti',
    nextTask: 'sekanti užduotis',
    finish: 'baigti',
    saveTask: 'išsaugoti',
    submitTasks: 'pateikti',
    reviewTasks: 'pasitikrinti',
    close: 'uždaryti',
    tryAgain: 'pakartoti',
    showResults: 'sprendimai',
    rateOnAppStore: 'įvertinkite programėlę',
    yes: 'Taip',
    no: 'Ne',
  },
  notifications: {
    enterNumber: 'Prašome įvesti skaičių',
    selectOperation: 'Pasirinkite bent vieną aritmetinį veiksmą',
    selectChallenge: 'Pasirinkite bent vieną aritmetinę užduotį',
    selectNumDigits1: 'Pasirinkite bent vieną skaitmenį pirmam kintamajam',
    selectNumDigits2: 'Pasirinkite bent vieną skaitmenį antram kintamajam',
    clearHistory: 'Ar tikrai norite ištrinti visą skaičiavimų istoriją?',
    historyIsEmpty: 'Jūsų istorija yra tuščia.',
  },
  numDigits: {
    title1: 'Pirmas skaičius',
    title2: 'Antras skaičius',
    one: 'vienženklis',
    two: 'dviženklis',
    three: 'triženklis',
    four: 'keturženklis',
  },
  numTasks: {
    title: 'Užduočių kiekis',
    ten: 'dešimt',
    twenty: 'dvidešimt',
    fifty: 'penkiasdešimt',
    hundred: 'šimtas',
  },
  operations: {
    title: 'Aritmetiniai veiksmai',
    addition: 'sudėtis',
    subtraction: 'atimtis',
    multiplication: 'daugyba',
    division: 'dalyba',
  },
  pageTitles: {
    hello: 'Labas!',
    settings: 'Nustatymai',
    task: 'Užduotis',
    outOf: 'iš',
    intermitResults: 'Tarpiniai rezultatai',
    results: 'Sprendimai',
    history: 'Istorija',
  },
  results: {
    title: 'Rezultatai',
    total: 'užduočių kiekis',
    correct: 'teisingi sprendimai',
    incorrect: 'neteisingi sprendimai',
    duration: 'sprendimo laikas',
  },
  sectionTitles: {
    selectLanguage: 'Pasirinkite kalbą',
  },
  statistics: {
    title: 'Statistika',
  },
  tasks: {
    title: 'Aritmetinės užduotys',
    solveA: 'rask pirmą skaičių',
    solveB: 'rask antrą skaičių',
    solveC: 'rask rezultatą',
  },
  developedBy: 'Programėlės autorius',
};
