export default {
  language: 'Русский',
  buttons: {
    start: 'начать',
    nextTask: 'следующая задача',
    finish: 'закoнчить',
    saveTask: 'сохранить',
    submitTasks: 'oтправить',
    reviewTasks: 'проверить',
    close: 'закрыть',
    tryAgain: 'повторить',
    showResults: 'решения',
    rateOnAppStore: 'оценить приложение',
    yes: 'Да',
    no: 'Нет',
  },
  notifications: {
    enterNumber: 'Пожалуйста, введите цифру',
    selectOperation: 'Выберите хотя бы одну арифметическую операцию',
    selectChallenge: 'Выберите хотя бы одну арифметическую задачу',
    selectNumDigits1: 'Выберите хотя бы одну цифру для первой переменной',
    selectNumDigits2: 'Выберите хотя бы одну цифру для второй переменной',
    clearHistory: 'Вы уверены, что хотите очистить всю историю?',
    historyIsEmpty: 'Ваша история пуста.',
  },
  numDigits: {
    title1: 'Первая цифра',
    title2: 'Вторая цифра',
    one: 'одна цифра',
    two: 'две цифры',
    three: 'три цифры',
    four: 'четыре цифры',
  },
  numTasks: {
    title: 'Количество задач',
    ten: 'десять',
    twenty: 'двадцать',
    fifty: 'пятьдесят',
    hundred: 'сто',
  },
  operations: {
    title: 'Арифметические операции',
    addition: 'добавление',
    subtraction: 'вычитание',
    multiplication: 'умножение',
    division: 'разделение',
  },
  pageTitles: {
    hello: 'Привет!',
    settings: 'Настройки',
    task: 'Задача',
    outOf: 'из',
    intermitResults: 'Промежуточные результаты',
    results: 'Решения',
    history: 'История',
  },
  results: {
    title: 'Результаты',
    total: 'количество задач',
    correct: 'правильные решения',
    incorrect: 'неправильные решения',
    duration: 'время решений',
  },
  sectionTitles: {
    selectLanguage: 'Выбрать язык',
  },
  statistics: {
    title: 'Статистика',
  },
  tasks: {
    title: 'Арифметические задачи',
    solveA: 'решить первую цифру',
    solveB: 'решить вторую цифру',
    solveC: 'найти результат',
  },
  developedBy: 'Разработчик',
};
